React home
Team-WHAK/frontend pull request #3
Opened 2023-06-23 21:46 UTC by wabowen89

2023-06-24 01:11 UTC, SunkissedQueen requested changes
Curious what is the difference between the current PascalCase react styling components and the components I see with the `.` separating each word. Ex: `<Nav.Item></Nav.Item>` and `<NavItem></NavItem>`?
Please look over the files for uniform indentation and proper nesting.

2023-06-24 11:26 UTC, kyloh1996 commented
Curious what is the difference between the current PascalCase react styling components and the components I see with the . separating each word. Ex: <Nav.Item></Nav.Item> and <NavItem></NavItem>?
There really isnt much of a difference. Nav.Item is from react suite and NavItem is from reactstrap. From What I gathered rsuite is just a newer version.

2023-06-26 17:43 UTC, SunkissedQueen commented on src/styles/NotFound.css
> +margin-left: 23vw;
look over indentation

2023-06-26 17:44 UTC, SunkissedQueen commented on src/styles/Footer.css
> +/* .R1 {}
do you need this commented out

2023-06-26 17:50 UTC, SunkissedQueen commented on src/styles/New.css
> +   padding-bottom: 9vw;
look at indentation

2023-06-26 18:04 UTC, kyloh1996 commented
Indentation has been updated and pushed

2023-06-26 21:49 UTC, SunkissedQueen requested changes
Look like you skipped one

2023-06-26 21:49 UTC, SunkissedQueen commented on src/styles/New.css
> +   padding-bottom: 9vw;
Looks like you missed one

2023-06-26 22:52 UTC, SunkissedQueen approved these changes

2023-06-26 22:53 UTC, merged