React new
Team-WHAK/frontend pull request #4
Opened 2023-06-23 22:01 UTC by wabowen89

2023-06-24 01:36 UTC, SunkissedQueen requested changes
I feel there might be some merge conflicts since files were changed on this branch that were also changed on a different branch. Similar questions from the other branch:
Curious what is the difference between the current PascalCase react styling components and the components I see with the . separating each word. Ex: <Nav.Item></Nav.Item> and <NavItem></NavItem>?
Please look over the files for uniform indentation, proper nesting, and commented code that you are not using.
I see that the components are accepting a lot of props. I did not notice where the data is being stored. Where are these props being passed?

2023-06-24 01:36 UTC, SunkissedQueen commented on src/pages/New.js
> +    Due_date: "",
attributes should be lowercase

2023-06-24 01:36 UTC, SunkissedQueen commented on src/_tests_/New.test.js
>  });
good approach to mock function

2023-06-24 11:29 UTC, kyloh1996 commented
I feel there might be some merge conflicts since files were changed on this branch that were also changed on a different branch

There was a merge conflict at one point but we handled it :)

2023-06-24 12:09 UTC, kyloh1996 commented on src/pages/New.js
> +    Due_date: "",
attributed have been downsized :P

2023-06-26 18:00 UTC, SunkissedQueen commented on src/pages/NotFound.js
>    );
indentation

2023-06-26 18:04 UTC, SunkissedQueen commented on src/styles/Home.css
> +}
indentation

2023-06-26 18:04 UTC, SunkissedQueen commented on src/styles/NotFound.css
> +}
indentation, commented out code

2023-06-26 22:54 UTC, SunkissedQueen approved these changes
Looks like there will be some merge conflict

2023-06-26 23:03 UTC, merged